services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    image: laravel-app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=secret

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
