# Usar uma imagem base do PHP com suporte a FPM
FROM php:8.2.27-fpm

# Instalar dependências necessárias para PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql

FROM node:16

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie os arquivos do frontend para o container
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Instale as dependências
RUN npm install

# Copie os arquivos restantes do frontend para o container
COPY ./frontend/ ./

# Copiar os arquivos do projeto para dentro do contêiner
COPY . /var/www/html/

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /var/www/html

# Instalar o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar dependências do Laravel
RUN composer install

# Expor a porta 9000 para o PHP-FPM
EXPOSE 9000

# Definir o comando para rodar o PHP-FPM
CMD ["php-fpm"]


