# Usando a imagem oficial do PHP
FROM php:8.2.27-fpm

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libpq-dev \
    git \
    unzip \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_pgsql

# Instalar o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Defina o diretório de trabalho no container
WORKDIR /app

# Definir o diretório de trabalho para o projeto Laravel
WORKDIR /var/www/html

# Copiar os arquivos do projeto para dentro do contêiner
COPY . /var/www/html/

# Instalar as dependências do Laravel
RUN composer install --no-dev --optimize-autoloader

# Expor a porta para o servidor web
EXPOSE 9000

# Iniciar o PHP-FPM
CMD ["php-fpm"]
